import Head from 'next/head';
import { ReactNode } from 'react';

import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import ApiTouchpointsButton from '@/components/api-touchpoints-button';
import { interFont } from '@/utils/fonts';

type Props = {
  children: ReactNode;
};

export default function DefaultLayout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Perk Party</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={`pt-16 ${interFont.className}`}>{children}</main>
      <ApiTouchpointsButton />
      <Footer />
    </>
  );
}
